문제 1

In [48]:
import numpy as np

Y = np.array([0.4, 2.0, 0.001, 0.32])

# softmax
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

print(softmax(Y))

[0.13250053 0.65627943 0.08890663 0.12231341]


문제 2

In [49]:
# output
pred = np.array([0.001, 0.9, 0.001, 0.098])
label = np.array([0, 0, 0, 1])

# mse
def mse(pred, label):
    return np.sum((pred - label)**2)

print(mse(pred, label))

# cd
def ce(pred, label):
    return -np.sum(label * np.log(pred))

print(ce(pred, label))

# log likelihood
def log_likelihood(pred, label):
    return np.sum(label * np.log(pred))

print(log_likelihood(pred, label))


1.623606
2.322787800311565
-2.322787800311565


문제 3

In [50]:
X = [[1, 1],
 [2, 3],
 [3, 3]]

X = np.array(X)

Y = np.array([3.0, 7.0, 8.8])

def ridge_regression(X, y, lam):
    # X: 입력 데이터 (n_samples, n_features)
    # y: 타겟 값 (n_samples,)
    # lam: 정규화 파라미터 (lambda)

    # X^T * X 계산
    XtX = np.dot(X.T, X)

    # 정규화 항 추가
    identity_matrix = np.eye(X.shape[1])  # 항등 행렬
    XtX_lam = XtX + (2 * lam * identity_matrix)

    # 역행렬 계산
    XtX_lam_inv = np.linalg.inv(XtX_lam)

    # 가중치 계산
    w_hat = np.dot(XtX_lam_inv, np.dot(X.T, y))

    return w_hat

print(ridge_regression(X, Y, 0.25))
print(ridge_regression(X, Y, 0.1))
print(ridge_regression(X, Y, 0.5))

[1.49158879 1.36074766]
[1.61538462 1.27884615]
[1.4 1.4]


lambda가 커질 수록 W가 크게 줄어든다.

문제 4

In [51]:
X = [[1, 1], [2, 2], [1, -1], [1, -2]]
Y = [-1.8, -3.6, 4.2, 7.2]

X = np.array(X)
Y = np.array(Y)

new_X = np.array([4, 4])

def pred(X, Y, lam, new_x):
    # X: 입력 데이터 (n_samples, n_features)
    # y: 타겟 값 (n_samples,)
    # lam: 정규화 파라미터 (lambda)

    W = ridge_regression(X, Y, lam)
    return np.dot(X, W), np.dot(new_x, W)

print(pred(X, Y, 0.25, new_X)) # 4-1
print(pred(X, Y, 0.125, new_X)) # 4-3
print(pred(X, Y, 0.5, new_X)) # 4-3

(array([-1.75785953, -3.51571906,  3.9090301 ,  6.74247492]), -7.0314381270903015)
(array([-1.7792    , -3.5584    ,  4.04906667,  6.9632    ]), -7.116799999999999)
(array([-1.71428571, -3.42857143,  3.65714286,  6.34285714]), -6.857142857142856)


문제 5

In [52]:
data = np.array([
    [121, 1.72, 69.0],
    [140, 1.62, 63.2],
    [120, 1.70, 59.0],
    [131, 1.80, 82.0],
    [101, 1.78, 73.5]
])

w = np.array([-0.01, 0.5, -0.23])
bias = 0



첫 번째 특성이 모델의 범위가 너무 커서 미치는 영향이 첫번째 특성에 크게 영향을 받을 것이다.

키가 모델의 예측에 큰 영향을 미치지만, 체중은 상대적으로 적은 영향을 미친다.

데이터의 스케일이 다르면 경사 하강법과 같은 최적화 알고리즘이 수렴하는 데 더 오랜 시간이 걸릴 수 있다.

In [53]:
# Z-score 정규화
mean = np.mean(data, axis=0)  # 각 특성의 평균
std = np.std(data, axis=0)     # 각 특성의 표준편차

z_score_normalized = (data - mean) / std

print(z_score_normalized)

[[-0.12277219 -0.06274558 -0.0423473 ]
 [ 1.33514753 -1.63138509 -0.76474234]
 [-0.1995048  -0.37647348 -1.28785599]
 [ 0.64455398  1.19216603  1.57681401]
 [-1.65742452  0.87843813  0.51813162]]


문제 6

각 합성곱 층의 필터 가중치는 He 초기화 방식으로 설정하고, 편향은 일반적으로 0으로 초기화한다.

문제 7

In [54]:
def nesterov_momentum(gradient_func, initial_theta, learning_rate, momentum, num_iterations):
    # 초기화
    theta = initial_theta
    v = np.zeros_like(theta)  # 모멘텀 초기화

    for i in range(num_iterations):

        # 기울기 계산
        gradient = gradient_func(theta)

        # 모멘텀 업데이트
        v = momentum * v + learning_rate * gradient

        # 최종 theta 업데이트
        theta = theta + v

    return theta

# theta + av 가 생략됬다.

문제 9

In [55]:
def nesterov_adam(gradient_func, initial_theta, learning_rate=0.001, beta1=0.9, beta2=0.999, epsilon=1e-8, num_iterations=1000):
    # 초기화
    theta = initial_theta
    v = np.zeros_like(theta)  # 모멘텀
    r = np.zeros_like(theta)  # 누적 제곱 기울기
    t = 0  # 반복 횟수

    for i in range(num_iterations):
        t += 1

        # Nesterov 모멘텀 적용
        theta = theta - beta1 * v

        # 기울기 계산
        gradient = gradient_func(theta)

        # 모멘텀 업데이트
        v = beta1 * v + (1 - beta1) * gradient

        # 누적 제곱 기울기 업데이트
        r = beta2 * r + (1 - beta2) * (gradient ** 2)

        # bias correction
        v_hat = v / (1 - beta1 ** t)
        r_hat = r / (1 - beta2 ** t)

        # 매개변수 업데이트
        theta -= learning_rate * v_hat / (np.sqrt(r_hat) + epsilon)

    return theta



문제 10

In [56]:
w = np.array([4.0, 2.0])
ro = 0.2

def j(w):
    w1 = w[0]
    w2 = w[1]
    return np.array([2*(w1-2), 8*(w2-1)])

w1 = w
w2 = w1 - ro*j(w1)
print(w2)

w3 = w2 - ro*j(w2)
print(w3)

w4 = w3 - ro*j(w3)
print(w4)

w5 = w4 - ro*j(w4)
print(w5)

w6 = w5 - ro*j(w5)
print(w6)

w7 = w6 - ro*j(w6)
print(w7)



[3.2 0.4]
[2.72 1.36]
[2.432 0.784]
[2.2592 1.1296]
[2.15552 0.92224]
[2.093312 1.046656]


문제 11

In [57]:
def generate_random_number(r):
    return np.random.uniform(-r, r)

문제 13

In [58]:
w1 = np.array([4.0, 2.0, 3.0])
ro = 0.2

def j(w):
    return np.array([4*(w[0]-2), 2*(w[1]-1), 4*(w[2]-1)])

w2 = w1 - ro*j(w1)
w2

array([2.4, 1.6, 1.4])

문제 14

In [59]:
import numpy as np
import sympy as sp

# 심파이에서 기호 변수 정의
w1, w2, w3 = sp.symbols('w1 w2 w3')

# 함수 정의
f = 2*(w1 - 2)**2 + (w2 - 1)**2 + 2*(w3 - 2)**2

# 해시언 행렬 계산
H = sp.hessian(f, (w1, w2, w3))

print("기호적 해시언 행렬:")
sp.pprint(H)

# 수치적으로 해시언 행렬 계산
# 예를 들어, (w1, w2, w3) = (1, 2, 3)에서의 해시언 행렬을 계산하고자 할 때:
H_numeric = H.subs({w1: 1, w2: 2, w3: 3})
H_numpy = np.array(H_numeric).astype(np.float64)

print("\n수치적 해시언 행렬 (w1=1, w2=2, w3=3):")
print(H_numpy)


기호적 해시언 행렬:
⎡4  0  0⎤
⎢       ⎥
⎢0  2  0⎥
⎢       ⎥
⎣0  0  4⎦

수치적 해시언 행렬 (w1=1, w2=2, w3=3):
[[4. 0. 0.]
 [0. 2. 0.]
 [0. 0. 4.]]


In [60]:
w1 = np.array([4.0, 2.0, 3.0])
ro = 0.2

def j(w):
    return np.array([4*(w[0]-2), 16*(w[1]-1),4*(w[2]-1)])

w2 = w1 - np.power(H_numpy, -1)*ro*j(w1)
w2

<ipython-input-60-35d2f6b23988>:7: RuntimeWarning: divide by zero encountered in power
  w2 = w1 - np.power(H_numpy, -1)*ro*j(w1)


array([[ 3.6, -inf, -inf],
       [-inf,  0.4, -inf],
       [-inf, -inf,  2.6]])