문제 1

In [ ]:
U^l, l=1 to L 초기화
repeat
    X와 Y에서 t개의 샘플을 무작위로 뽑아 미니배치 X'와 Y'를 만든다

    for l in range(1, L):
        \delta U^l = 0

    현재 처리하는 샘플을 x= (x_0, x_1, x_2, ...)^T, y= (y_0, y_1, y_2 ..)^T 라 표기한다
    x_0 = z_0 = 1
    for l in (1, L):
        S^l = U^l*Z^{l-1}
        Z^l = tau_l(S^l)
    delta_L = tau_L(S^L)(Y-O)
    delta_U^L += -delta^L * Z^L-1

    for l in range(L-1, 1, -1):
        delta_l = tau^'_l (S^l) sum_p=1^n_l+1 delta^l+1_p * u_p^l+1
        delta_u^l += -delta_l * Z^l-1

    for l in range(L, 1, -1):
        U^l -= rou(1/t) * delta U^l

until (stop_condition)

문제 2

$$ \left( \mathbf{X}_c \ast \mathbf{W}c \right)(i, j) = \sum{y=-(h-1)/2}^{(h-1)/2} \sum{x=-(h-1)/2}^{(h-1)/2} X_c(i + y, j + x) \cdot W_c(y, x) $$

$$  \left( \mathbf{X}c \ast \mathbf{W}c \right)(t, i, j) = \sum{z=-(h-1)/2}^{(h-1)/2} \sum{y=-(h-1)/2}^{(h-1)/2} \sum_{x=-(h-1)/2}^{(h-1)/2} X_c(t + z, i + y, j + x) \cdot W_c(z, y, x)  $$

문제 3

1. 컨볼루션 레이어 적용:  
•	입력 이미지에 여러 층의 컨볼루션과 풀링 레이어를 적용하여 특징 맵을 생성합니다. 이 단계는 일반적인 CNN과 동일합니다.


2.	Spatial Pyramid Pooling 레이어 적용:  
•	생성된 특징 맵에 대해 SPP 레이어를 적용합니다. SPP는 다양한 크기의 풀링 윈도우를 사용하여 입력 특징 맵을 여러 레벨로 나누고, 각 레벨에서 고정된 크기의 출력을 생성합니다.  
•	예를 들어, SPP는 (1 \times 1), (2 \times 2), (4 \times 4) 등 다양한 크기의 풀링 윈도우를 사용할 수 있습니다.  
•	각 풀링 윈도우는 해당 영역 내에서 최대값을 선택하는 Max Pooling을 적용합니다.  


3.	고정된 크기의 벡터 생성:  
•	각 레벨에서 생성된 풀링 결과는 고정된 크기의 벡터로 변환됩니다. 이 벡터들은 모두 연결(concatenate)되어 최종적으로 고정된 크기의 하나의 벡터를 형성합니다.  
•	이 벡터는 이후의 완전 연결 층(fully connected layer)으로 전달되어 학습과 분류 작업에 사용됩니다.  

문제 4

당시에 컴퓨팅 파워가 부족 또한 지금처럼 인터넷을 기반으로 거대한 데이터셋을 얻을 수 없었음.

문제 5

In [2]:
import numpy as np

# 입력값
x = np.array([1, 1, 1])

# 은닉층 1 가중치
w1 = np.array([
    [0.3, 1.0, 1.0],
    [1.2, -1.0, 1.6],
    [-1.1, 0.5, 0.1]
])

# 은닉층 2 가중치
w2 = np.array([
    [-0.8, 0.7, 1.0],
    [0.1, -0.1, 0.3],
    [0.1, 1.0, 0.2]
])

# 은닉층 3 가중치
w3 = np.array([
    [1.0, -0.2],
    [0.1, -0.1],
    [1.3, 0.2]
])

# 출력층 가중치
wo = np.array([
    [1.0, 0.4],
    [-0.4, 1.0]
])

# 활성화 함수
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 은닉층 1 출력
h1 = sigmoid(np.dot(x, w1))

# 은닉층 2 출력
h2 = sigmoid(np.dot(h1, w2))

# 은닉층 3 출력
h3 = sigmoid(np.dot(h2, w3))

# 출력층 출력
o = sigmoid(np.dot(h3, wo))

print("은닉층 1 출력:", h1)
print("은닉층 2 출력:", h2)
print("은닉층 3 출력:", h3)
print("출력층 출력:", o)

은닉층 1 출력: [0.59868766 0.62245933 0.93702664]
은닉층 2 출력: [0.41994443 0.78480017 0.72568337]
은닉층 3 출력: [0.80873522 0.49566705]
출력층 출력: [0.64804764 0.69405824]


$$ 은닉층 1의 가중치 행렬 ( U1 ):


U1 = \begin{bmatrix}
0.3 & 1.0 & 1.0 \\
1.2 & -1.0 & 1.6 \\
-1.1 & 0.5 & 0.1
\end{bmatrix}


은닉층 2의 가중치 행렬 ( U2 ):


U2 = \begin{bmatrix}
-0.8 & 0.7 & 1.0 \\
0.1 & -0.1 & 0.3 \\
0.1 & 1.0 & 0.2
\end{bmatrix}


은닉층 3의 가중치 행렬 ( U3 ):


U3 = \begin{bmatrix}
1.0 & -0.2 \\
0.1 & -0.1 \\
1.3 & 0.2
\end{bmatrix}


출력층의 가중치 행렬  U4 :


U4 = \begin{bmatrix}
1.0 & 0.4 \\
-0.4 & 1.0
\end{bmatrix}
$$

In [3]:
x = np.array([1, 1, 0])

# 은닉층 1 출력
h1 = sigmoid(np.dot(x, w1))

# 은닉층 2 출력
h2 = sigmoid(np.dot(h1, w2))

# 은닉층 3 출력
h3 = sigmoid(np.dot(h2, w3))

# 출력층 출력
o = sigmoid(np.dot(h3, wo))
o

array([0.64783011, 0.69479754])

문제 6

성능 평가 기준

ILSVRC 대회에서 물체 검출 성능 평가에 사용되는 주요 기준은 다음과 같습니다:

	1.	정확도(Average Precision, AP): 특정 임계값에서 객체 검출의 정밀도(Precision)와 재현율(Recall)을 기반으로 계산됩니다.
	2.	평균 정밀도(Mean Average Precision, mAP): 다양한 임계값에서의 AP를 평균한 값으로, 전체 모델의 성능을 평가하는 지표입니다. 여러 클래스에 대해 mAP를 계산하여 전체적인 성능을 측정합니다.

최근 성능

최근 ILSVRC 대회에서 달성된 성능을 보면, 최신 모델들은 높은 정확도와 빠른 속도로 뛰어난 성과를 보여주고 있습니다. 예를 들어, 2023년 ILSVRC 대회에서는 Transformer 기반 모델들이 우수한 성능을 보였습니다. 최신 연구에서는 ViT (Vision Transformer) 모델과 같은 새로운 아키텍처가 등장하면서, 물체 검출 성능이 크게 향상되었습니다.

문제 7

In [1]:
import numpy as np

# 입력 이미지 (R, G, B 채널)
R = np.array([
    [1, 1, 1],
    [2, 1, 3],
    [0, 1, 0]
])

G = np.array([
    [2, 2, 2],
    [1, 0, 3],
    [1, 0, 1]
])

B = np.array([
    [0, 3, 0],
    [1, 0, 1],
    [0, 1, 0]
])

# 커널
kernel_R = np.array([
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0]
])

kernel_G = np.array([
    [0, 2, 0],
    [0, 2, 0],
    [0, 2, 0]
])

kernel_B = np.array([
    [1, 0, 0],
    [0, 2, 0],
    [0, 0, 1]
])

# 패딩을 추가한 이미지
def pad_image(image, pad_width=1):
    return np.pad(image, pad_width, mode='constant', constant_values=0)

R_padded = pad_image(R)
G_padded = pad_image(G)
B_padded = pad_image(B)

# 컨볼루션 연산 수행
def convolution(image, kernel):
    kernel_size = kernel.shape[0]
    output_size = image.shape[0] - kernel_size + 1
    output = np.zeros((output_size, output_size))
    for i in range(output_size):
        for j in range(output_size):
            output[i, j] = np.sum(image[i:i+kernel_size, j:j+kernel_size] * kernel)
    return output

# 각 채널에 대해 컨볼루션 수행
conv_R = convolution(R_padded, kernel_R)
conv_G = convolution(G_padded, kernel_G)
conv_B = convolution(B_padded, kernel_B)

# 최종 특징 맵 계산
feature_map = conv_R + conv_G + conv_B

print("패딩된 R 채널:\n", R_padded)
print("패딩된 G 채널:\n", G_padded)
print("패딩된 B 채널:\n", B_padded)
print("R 채널의 컨볼루션 결과:\n", conv_R)
print("G 채널의 컨볼루션 결과:\n", conv_G)
print("B 채널의 컨볼루션 결과:\n", conv_B)
print("최종 특징 맵:\n", feature_map)

패딩된 R 채널:
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 2 1 3 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
패딩된 G 채널:
 [[0 0 0 0 0]
 [0 2 2 2 0]
 [0 1 0 3 0]
 [0 1 0 1 0]
 [0 0 0 0 0]]
패딩된 B 채널:
 [[0 0 0 0 0]
 [0 0 3 0 0]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
R 채널의 컨볼루션 결과:
 [[3. 2. 3.]
 [1. 4. 0.]
 [1. 0. 0.]]
G 채널의 컨볼루션 결과:
 [[ 6.  4. 10.]
 [ 8.  4. 12.]
 [ 4.  0.  8.]]
B 채널의 컨볼루션 결과:
 [[0. 7. 0.]
 [3. 0. 5.]
 [0. 3. 0.]]
최종 특징 맵:
 [[ 9. 13. 13.]
 [12.  8. 17.]
 [ 5.  3.  8.]]


문제 8

In [4]:
import numpy as np

# 주어진 행렬
input_matrix = np.array([
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9]
])

# 커널
kernel = np.array([
    [-1, -1, -1],
    [0, 0, 0],
    [1, 1, 1]
])

# 패딩 적용
def pad_image(image, pad_width=1):
    return np.pad(image, pad_width, mode='constant', constant_values=0)

padded_input = pad_image(input_matrix)

# 컨볼루션 연산 함수
def convolution(image, kernel, bias=0.5):
    kernel_size = kernel.shape[0]
    output_size = image.shape[0] - kernel_size + 1
    output = np.zeros((output_size, output_size))
    for i in range(output_size):
        for j in range(output_size):
            output[i, j] = np.sum(image[i:i+kernel_size, j:j+kernel_size] * kernel) + bias
    return output

# 컨볼루션 연산 수행
output_feature_map = convolution(padded_input, kernel)

print("패딩된 입력 행렬:\n", padded_input)
print("특징 맵:\n", output_feature_map)

패딩된 입력 행렬:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 0 0 0 0 0 0 0 0 0]]
특징 맵:
 [[  4.5   6.5   6.5   5.5   4.5   3.5   3.5   2.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [  0.5   0.5   7.5  15.5  23.5  24.5  24.5  16.5]
 [  0.5   0.5   7.5  15.5  23.5  24.5  24.5  16.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [ -3.5  -5.5 -12.5 -19.5 -26.5 -26.5 -26.5 -17.5]]


문제 9

In [5]:
import numpy as np

# 주어진 행렬
input_matrix = np.array([
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9]
])

# 커널
kernel = np.array([
    [-1, -1, -1],
    [0, 0, 0],
    [1, 1, 1]
])

# 패딩 적용
def pad_image(image, pad_width=1):
    return np.pad(image, pad_width, mode='constant', constant_values=0)

padded_input = pad_image(input_matrix)

# 컨볼루션 연산 함수 (stride=2)
def convolution(image, kernel, stride=2, bias=0.5):
    kernel_size = kernel.shape[0]
    output_size = (image.shape[0] - kernel_size) // stride + 1
    output = np.zeros((output_size, output_size))
    for i in range(0, output_size * stride, stride):
        for j in range(0, output_size * stride, stride):
            output[i // stride, j // stride] = np.sum(image[i:i+kernel_size, j:j+kernel_size] * kernel) + bias
    return output

# 컨볼루션 연산 수행 (stride=2)
output_feature_map = convolution(padded_input, kernel, stride=2)

print("패딩된 입력 행렬:\n", padded_input)
print("특징 맵:\n", output_feature_map)

패딩된 입력 행렬:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 0 0 0 0 0 0 0 0 0]]
특징 맵:
 [[ 4.5  6.5  4.5  3.5]
 [ 0.5  0.5  0.5  0.5]
 [ 0.5  7.5 23.5 24.5]
 [ 0.5  0.5  0.5  0.5]]


문제 10

In [6]:
import numpy as np

# 주어진 행렬
input_matrix = np.array([
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 2, 1, 1, 1, 1],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9]
])

# 커널
kernel = np.array([
    [-1, -1, -1],
    [0, 0, 0],
    [1, 1, 1]
])

# 패딩 적용
def pad_image(image, pad_width=1):
    return np.pad(image, pad_width, mode='constant', constant_values=0)

padded_input = pad_image(input_matrix)

# 컨볼루션 연산 함수
def convolution(image, kernel, bias=0.5):
    kernel_size = kernel.shape[0]
    output_size = image.shape[0] - kernel_size + 1
    output = np.zeros((output_size, output_size))
    for i in range(output_size):
        for j in range(output_size):
            output[i, j] = np.sum(image[i:i+kernel_size, j:j+kernel_size] * kernel) + bias
    return output

# 컨볼루션 연산 수행
conv_result = convolution(padded_input, kernel)

# Max Pooling 함수
def max_pooling(image, pool_size=2):
    output_size = image.shape[0] // pool_size
    output = np.zeros((output_size, output_size))
    for i in range(output_size):
        for j in range(output_size):
            output[i, j] = np.max(image[i*pool_size:(i+1)*pool_size, j*pool_size:(j+1)*pool_size])
    return output

# Average Pooling 함수
def avg_pooling(image, pool_size=2):
    output_size = image.shape[0] // pool_size
    output = np.zeros((output_size, output_size))
    for i in range(output_size):
        for j in range(output_size):
            output[i, j] = np.mean(image[i*pool_size:(i+1)*pool_size, j*pool_size:(j+1)*pool_size])
    return output

# Max Pooling 연산 수행
max_pool_result = max_pooling(conv_result)

# Average Pooling 연산 수행
avg_pool_result = avg_pooling(conv_result)

print("패딩된 입력 행렬:\n", padded_input)
print("컨볼루션 결과:\n", conv_result)
print("Max Pooling 결과:\n", max_pool_result)
print("Average Pooling 결과:\n", avg_pool_result)

패딩된 입력 행렬:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 2 1 1 1 1 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 2 2 2 9 9 9 9 9 0]
 [0 0 0 0 0 0 0 0 0 0]]
컨볼루션 결과:
 [[  4.5   6.5   6.5   5.5   4.5   3.5   3.5   2.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [  0.5   0.5   7.5  15.5  23.5  24.5  24.5  16.5]
 [  0.5   0.5   7.5  15.5  23.5  24.5  24.5  16.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [ -3.5  -5.5 -12.5 -19.5 -26.5 -26.5 -26.5 -17.5]]
Max Pooling 결과:
 [[ 6.5  6.5  4.5  3.5]
 [ 0.5 15.5 24.5 24.5]
 [ 0.5 15.5 24.5 24.5]
 [ 0.5  0.5  0.5  0.5]]
Average Pooling 결과:
 [[  3.     3.25   2.25   1.75]
 [  0.5    6.    12.25  10.5 ]
 [  0.5    6.    12.25  10.5 ]
 [ -2.    -7.75 -13.   -10.75]]
